/*

Consultas que criei da minha cabeça, as de desafio do curso da alura, e as de aula

*/



/*SELECT CPF, NOME, LIMITE_DE_CREDITO FROM TABELA_DE_CLIENTES
WHERE LIMITE_DE_CREDITO >= 120000;*/

--SELECT * FROM TABELA_DE_PRODUTOS WHERE EMBALAGEM = 'pet';

/*SELECT TABELA_DE_VENDEDORES.MATRICULA,TABELA_DE_VENDEDORES.NOME ,SUM(TABELA_DE_VENDEDORES.PERCENTUAL_COMISSAO * 1.1) AS COMISSAO
FROM TABELA_DE_VENDEDORES
WHERE TABELA_DE_VENDEDORES.DE_FERIAS = 1
GROUP BY TABELA_DE_VENDEDORES.MATRICULA, TABELA_DE_VENDEDORES.NOME ;*/

/*SELECT DISTINCT TABELA_DE_PRODUTOS.NOME_DO_PRODUTO, TABELA_DE_CLIENTES.CPF, TABELA_DE_CLIENTES.NOME, ITENS_NOTAS_FISCAIS.QUANTIDADE
FROM TABELA_DE_CLIENTES, NOTAS_FISCAIS, ITENS_NOTAS_FISCAIS 
INNER JOIN TABELA_DE_PRODUTOS ON  ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO = TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO
WHERE TABELA_DE_CLIENTES.NOME = 'Valdeci da Silva';*/


/*SELECT DISTINCT TABELA_DE_VENDEDORES.NOME, TABELA_DE_VENDEDORES.MATRICULA, SUM(ITENS_NOTAS_FISCAIS.QUANTIDADE) AS VENDAS
FROM TABELA_DE_VENDEDORES, ITENS_NOTAS_FISCAIS
INNER JOIN NOTAS_FISCAIS ON NOTAS_FISCAIS.NUMERO = ITENS_NOTAS_FISCAIS.NUMERO
GROUP BY TABELA_DE_VENDEDORES.NOME, TABELA_DE_VENDEDORES.MATRICULA;*/

/*SELECT TABELA_DE_CLIENTES.CPF,TABELA_DE_CLIENTES.NOME,TABELA_DE_CLIENTES.ESTADO, TABELA_DE_CLIENTES.PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES
WHERE TABELA_DE_CLIENTES.PRIMEIRA_COMPRA = 1 AND TABELA_DE_CLIENTES.ESTADO = 'RJ';*/

/*SELECT TABELA_DE_PRODUTOS.SABOR, TABELA_DE_PRODUTOS.NOME_DO_PRODUTO, TABELA_DE_PRODUTOS.PRECO_DE_LISTA
FROM TABELA_DE_PRODUTOS
WHERE TABELA_DE_PRODUTOS.SABOR LIKE '%Maca'
*/

/*SELECT COUNT(TABELA_DE_CLIENTES.NOME) AS Silvas FROM TABELA_DE_CLIENTES
WHERE TABELA_DE_CLIENTES.NOME LIKE '%Silva';*/

--SELECT DISTINCT TABELA_DE_PRODUTOS.SABOR FROM TABELA_DE_PRODUTOS;

--SELECT DISTINCT TOP 4 TABELA_DE_PRODUTOS.SABOR FROM TABELA_DE_PRODUTOS

/*SELECT TOP 10 ITENS_NOTAS_FISCAIS.QUANTIDADE, NOTAS_FISCAIS.DATA_VENDA
FROM NOTAS_FISCAIS
INNER JOIN  ITENS_NOTAS_FISCAIS ON ITENS_NOTAS_FISCAIS.NUMERO = NOTAS_FISCAIS.NUMERO
WHERE NOTAS_FISCAIS.DATA_VENDA = '2017-10-01';*/


/*SELECT TABELA_DE_PRODUTOS.NOME_DO_PRODUTO, TABELA_DE_PRODUTOS.SABOR, TABELA_DE_PRODUTOS.TAMANHO, ITENS_NOTAS_FISCAIS.QUANTIDADE
FROM TABELA_DE_PRODUTOS
INNER JOIN ITENS_NOTAS_FISCAIS ON TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO = ITENS_NOTAS_FISCAIS.CODIGO_DO_PRODUTO
WHERE TABELA_DE_PRODUTOS.CODIGO_DO_PRODUTO = '1101035'
ORDER BY ITENS_NOTAS_FISCAIS.QUANTIDADE DESC;*/

--SELECT COUNT(*) FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99;

/*SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO ORDER BY SUM(QUANTIDADE) DESC;*/

/*SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QUANTIDADE FROM ITENS_NOTAS_FISCAIS 
GROUP BY CODIGO_DO_PRODUTO HAVING SUM(QUANTIDADE) > 394000 
ORDER BY SUM(QUANTIDADE) DESC;*/

/*SELECT TABELA_DE_PRODUTOS.NOME_DO_PRODUTO, TABELA_DE_PRODUTOS.PRECO_DE_LISTA,
(CASE WHEN TABELA_DE_PRODUTOS.PRECO_DE_LISTA >= 12.00 THEN 'CARO'
	WHEN TABELA_DE_PRODUTOS.PRECO_DE_LISTA >= 7.00 AND TABELA_DE_PRODUTOS.PRECO_DE_LISTA< 12.00 THEN 'OK'
	ELSE 'BARATO' END) AS CLASSIFICAÇÃO
	FROM TABELA_DE_PRODUTOS
	WHERE SABOR = 'MANGA'
	ORDER BY PRECO_DE_LISTA DESC;
	*/
	/*SELECT 
(CASE WHEN PRECO_DE_LISTA >12 THEN 'CARO' 
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'OK' 
      ELSE 'BARATO' END) AS CLASSIFICACAO, COUNT(*) AS NUMERO_DE_PRODUTOS 
FROM TABELA_DE_PRODUTOS 
GROUP BY (CASE WHEN PRECO_DE_LISTA >12 THEN 'CARO' 
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'OK' 
      ELSE 'BARATO' END); */
	  
	  
	  
	  /*SELECT DISTINCT TABELA_DE_CLIENTES.BAIRRO, 'CLIENTE' AS ORIGEM FROM TABELA_DE_CLIENTES 
		UNION 
	  SELECT DISTINCT TABELA_DE_VENDEDORES.BAIRRO, 'FORNECEDOR' AS ORIGEM FROM TABELA_DE_VENDEDORES;*/


